export const Icons = {
  administration: "/assets/icons/administration.svg",
  book: "/assets/icons/book.svg",
  comments: "/assets/icons/comments.svg",
  contract: "/assets/icons/contract.svg",
  dropdown: "/assets/icons/arrow-down.svg",
  ecosystem: "/assets/icons/ecosystem.svg",
  entities: "/assets/icons/entities.svg",
  home: "/assets/icons/house.svg",
  logo: "/assets/logo-alt.png",
  logout: "/assets/icons/logout.svg",
  network: "/assets/icons/network.png",
  notification: "/assets/icons/bell.svg",
  plus: "/assets/icons/plus.svg",
  privacy: "/assets/icons/privacy.svg",
  settings: "/assets/icons/settings.svg",
  search: "/assets/icons/search.svg",
  userAdd: "/assets/icons/user-plus.svg",
  yourPublications: "/assets/icons/yourpublications.png",
  mosaic: "/assets/icons/mosaic.svg",
  list: "/assets/icons/list.svg",
  all: "/assets/icons/all.svg",
  more: "/assets/icons/more.svg",
  sort: "/assets/icons/sort.svg",
  filter: "/assets/icons/filter.svg",
  resize: "/assets/icons/resize.svg",
  share: "/assets/icons/share.svg",
  signal: "/assets/icons/signal.svg",
};

export default Icons;
